services:
  # caddy:
  #   image: caddy:latest
  #   restart: unless-stopped
  #   container_name: caddy
  #   env_file:
  #     - .env
  #   ports:
  #     - ${CADDY_PORT_HTTP}:80
  #     - ${CADDY_PORT_HTTPS}:443
  #   networks:
  #     - caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./site:/srv
  #     - caddy_data:/data
  #     - caddy_config:/config

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - caddy
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:80"
    networks:
      - caddy
    volumes:
      - .:/app/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    networks:
      - caddy
    volumes:
      - .:/app/

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  caddy: